# Generated by Django 4.0.5 on 2023-03-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rp', models.IntegerField()),
                ('mp', models.IntegerField()),
            ],
        ),
    ]
